Setup prisma and made erd entities
TEAM-LEG3ND/studium-server pull request #12
Opened 2023-06-11 17:08 UTC by ammerss

Changes Made:
- I set up Prisma which will work as a bridge between our Postgres database and our backend service. 
    Mainly following this blogpost : https://www.tomray.dev/nestjs-prisma

- I created tables in [schema.prisma](src/database/schema.prisma) that are defined from our ERD.
ERD : https://app.diagrams.net/#G1Nl9baCsEKaVKwI-ZyPxtif42b7W0BiMy
    - Some fields in ERD that were not added yet -
    Study : study_template
    User : skill_tags, shared_posts

- Some architectural designs included  : 
    - repository layer, service layer
    - separate api module for api endpoints

- Database is configured in env. file to @d0lim's dev server
- I deleted previous files that were made before Prisma was configured. 
- I have also written simple apis for User Create and User Get.

Next Step Ideas: 
- DTO
- pagination
- unit testing

2023-06-12 11:14 UTC, selgyun commented
파일 명을 user가 아니라 modules/user로 한 이유가 궁금합니다.

2023-06-12 13:38 UTC, redjen8 requested changes
수고하셨습니다~! 쉽지 않은 prisma 초기 설정이었을텐데, 끝까지 잘 해내주셔서 감사합니다.
코드 전반적으로 eslint prettier 설정이 되었으면 좋겠습니다.
저는 개인적으로 vscode 코드 저장 시에 자동으로 prettier가 적용되도록 설정해놨는데, 아래 링크 참고해보시면 좋을 것 같아요 😀
https://www.robinwieruch.de/how-to-use-prettier-vscode/

2023-06-12 13:38 UTC, redjen8 commented on src/api/api.controller.ts
> +        const studyIdArray = [Number(study_joined)];
`NumberConstructor`를 통해서 생성된 복수의 `number` 데이터가 array에 들어가 있는 형태인 것 같은데, 혹시 중복 데이터에 대한 처리는 어떻게 수행하나요? (ex. "study_joined": ["1", "1", "2"] 가 body로 들어온 경우)

2023-06-12 13:38 UTC, redjen8 commented on src/api/api.controller.ts
> +        membersOf : membersIdArray,
dto에 대한 네이밍 통일화가 논의되어야 하는 시점인 것 같습니다.
되도록이면 camelCase로 dto 필드명을 통일하면 어떨까요? (study_joined -> studyJoined)

2023-06-12 13:38 UTC, redjen8 commented on src/api/api.controller.ts
> +        return this.userService.getUsers();
이 API는 테스트 목적인지 궁금합니다.

2023-06-12 16:11 UTC, d0lim commented on src/api/api.controller.ts
> +export class ApiController {
이번에 하는게 아니라 다음 feature로 잡고 가도 좋습니다.

2023-06-12 16:59 UTC, d0lim approved these changes

2023-06-12 18:54 UTC, ammerss commented on src/api/api.controller.ts
> +        return this.userService.getUsers();
테스트목적입니다

2023-06-12 19:11 UTC, ammerss commented on src/api/api.controller.ts
> +        membersOf : membersIdArray,
camelCase로 고쳤습니다

2023-06-12 19:13 UTC, ammerss commented on src/api/api.controller.ts
> +export class ApiController {
다음에 하겠습니다

2023-06-13 08:10 UTC, redjen8 commented on src/api/api.controller.ts
> +        const studyIdArray = [Number(study_joined)];
prisma orm 매핑 시에 해당 키로 '사용자가 소속된 study 목록을 구할 때'와 같이 join이 필요한 경우라면 문제가 될 수 있을 것 같습니다.
최소한의 정합성을 위해서는 controller 레벨에서의 검증이 어느정도 있어야 된다고 생각합니다. (현재 서비스 레이어로 분리가 되어 있지 않기 떄문에)

2023-06-13 14:09 UTC, d0lim approved these changes

2023-06-13 14:32 UTC, redjen8 commented
prettier 적용해주세요~

2023-06-19 14:05 UTC, redjen8 approved these changes
수고하셨습니다~!

2023-06-19 14:07 UTC, d0lim approved these changes

2023-06-19 14:07 UTC, d0lim commented
Squash Merge 될 수 있도록 부탁드릴게요

2023-06-19 14:08 UTC, merged