Warmup 시점에 인증서버에 public endpoint 전달 기능 개발
TEAM-LEG3ND/studium-server pull request #61
Opened 2023-08-10 13:02 UTC by redjen8

애플리케이션 부트스트랩 시점에 인증 서버 (turntile)에 public 및 draft api endpoint 목록 전달하는 기능을 개발합니다.

https://api.server.d0lim.com/turnstile/swagger-ui/index.html

2023-08-11 02:11 UTC, selgyun submitted a review, later dismissed

2023-08-11 07:18 UTC, redjen8 commented
https://github.com/prisma/prisma/issues/20171

axios import 하며 prisma 5.0.0 버전 업데이트도 같이 되며 기존 `shutdownHook`에도 변경이 있었는데요,
해당 건 변경 본 이슈에서 반영한 후 머지하도록 하겠습니다.

(또는 prisma 버전을 4.x.x 대로 다시 원복하는 게 좋을까요? 개인적으론 특별한 이슈가 없다면 최신 릴리즈 버전을 사용하는 것이 맞다고 생각듭니다)

2023-08-11 17:37 UTC, d0lim approved these changes
고생하셨습니다.

저는 Prisma 최신 버전 F/U 하는게 좋을 것 같네요.

프로젝트의 목적이 안정적인 프로덕트 개발보다는 기술적 성장에 방점을 두고 있으니, 가급적 최신 기술에 대한 감각을 익히는 편이 더 좋을 것 같습니다. 문제가 생기면 해결해보는 경험도 덤이구요.

2023-08-13 04:54 UTC, d0lim commented on src/common/warmup/warmup.service.ts
> +      name: 'STUDIUM',
해당 필드의 key를 `serviceType` 으로 변경했습니다. 반영 부탁드릴게요.
스펙이 휙휙 바껴서 죄송합니다 ㅠ

2023-08-13 04:56 UTC, d0lim requested changes
[요거](https://github.com/TEAM-LEG3ND/studium-server/pull/61/files#r1292654118)만 반영 부탁드립니다.

2023-08-13 04:56 UTC, d0lim commented on src/common/warmup/warmup.service.ts
> +      name: 'STUDIUM',
```suggestion
      serviceType: 'STUDIUM',
```

2023-08-14 13:12 UTC, d0lim commented on src/common/warmup/warmup.service.ts
> +      serviceType: 'STUDIUM',
한번 돌려보시고 말씀주세요...

2023-08-14 13:37 UTC, redjen8 commented on src/common/warmup/warmup.service.ts
> +      serviceType: 'STUDIUM',
하하하하

2023-08-14 13:38 UTC, redjen8 commented on src/common/warmup/warmup.service.ts
> +      serviceType: 'STUDIUM',
동작되는 것 확인했습니다

2023-08-14 14:18 UTC, ammerss approved these changes

2023-08-17 01:13 UTC, selgyun approved these changes

2023-08-17 12:14 UTC, d0lim commented on src/common/warmup/warmup.service.ts
> +      serviceType: 'STUDIUM',
머지 가시죱..!

2023-08-17 13:25 UTC, merged