[PR][#48] 인기 스터디 조회 API
TEAM-LEG3ND/studium-server pull request #64
Opened 2023-08-17 02:41 UTC by selgyun

2023-08-17 12:14 UTC, d0lim requested changes

2023-08-17 12:14 UTC, d0lim commented on src/study/dto/create-study.dto.ts
> +  readonly viewCount: number;
스터디 만들 때 필요한 DTO는 아니지 싶은데요. 빼버리고 로직 안에서 기본값 0으로 초기화 하는건 어떨까요?

2023-08-17 12:14 UTC, d0lim commented on src/study/dto/update-study-response.dto.ts
> +    viewCount: number,
마찬가지로 조회수는 수정이 불가해야할 것 같아요.

2023-08-17 12:14 UTC, d0lim commented on src/study/study.service.ts
> +          increment: 1
`increment` 사용 시 혹시 어떤 쿼리가 나가는지 확인하셨나요?
MySQL `SET viewCount = viewCount + 1` 쿼리가 나가면 좋을텐데, 아니라면 동시성 문제가 발생할 수 있어서 수정이 필요할 것 같습니다.

2023-08-18 00:42 UTC, selgyun commented on src/study/study.service.ts
> +          increment: 1
![image](https://github.com/TEAM-LEG3ND/studium-server/assets/29320054/fbbf3eac-785c-4d65-9e38-066efec81cfb)
올바른 쿼리가 생성되는 것 같습니다.

2023-08-18 00:45 UTC, selgyun commented on src/study/dto/create-study.dto.ts
> +  readonly viewCount: number;
수정했습니다. prisma default 값으로 0을 넣고 있습니다. 생성 dto에서는 삭제했습니다 .

2023-08-18 00:45 UTC, selgyun commented on src/study/dto/update-study-response.dto.ts
> +    viewCount: number,
응답 dto라 상관 없는 거 아닌가요?

2023-08-18 00:53 UTC, d0lim commented on src/study/dto/update-study-response.dto.ts
> +    viewCount: number,
아이고;; 맞네요. 잘못 봤습니다 ㅜ

2023-08-18 00:53 UTC, d0lim approved these changes

2023-08-18 05:34 UTC, redjen8 approved these changes
수고하셨습니다~ 
자칫 복잡할 수 있는 조회수 증가 / 조회 로직을 추가적인 리소스 투입 없이 잘 구현하신 것 같습니다.

2023-08-18 05:34 UTC, redjen8 commented on src/study/study.service.ts
> +        }
prisma where gte 조건에 human readable 한 date 조건이 들어갈 수 있군요~ 👍

2023-08-18 05:34 UTC, redjen8 commented on src/study/study.service.ts
> +          increment: 1
꼼꼼한 확인 감사합니다.

2023-08-18 07:57 UTC, merged